"""
cdmx_wc2026_real_validation_distance_decay.py -- FORK of
cdmx_wc2026_real_validation.py (does not modify the original), swapping the
`is_venue_line` feature for the `distance_decay` variant developed for R2.4
(see src/paper/tier2/cdmx_gnn_loto_catchment_fix.py).

Purpose: the R2.4 fix (distance-decay-weighted line indicator instead of a
coarse same-line binary) was validated on LOTO-CV (12 seeds: no accuracy
regression, p=0.058 trending better, and it resolves the flagged Tlaltenco
leakage). But the paper's headline real-world-validation table
(tab:real_wc2026, the 4 real WC2026 matches already played) is generated by
a SEPARATE RF model (this script), trained on the same 6-feature vector.
That table's numbers (-23.7% mean, retraction of the Tasqueña correction)
are the central finding of this revision cycle. Before touching the
manuscript's cited numbers, this fork regenerates that exact same
comparison with distance_decay instead of is_venue_line, so we can check
honestly whether the finding (model underperforms naive baseline on all 4
real matches) survives the feature swap or changes.

Everything else (RF hyperparameters, training set, real ridership data,
methodology) is IDENTICAL to the original script -- only F[2] changes.

Output: outputs/paper/cdmx/cdmx_wc2026_real_validation_distance_decay.csv
"""
from __future__ import annotations
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "src"))

import numpy as np
import pandas as pd

from src.paper.tier2.cdmx_gnn_loto import (
    load_data, get_observed_spatial_distribution,
    historical_avg_baseline, VENUE_CATCHMENT,
)
from src.paper.tier2.cdmx_gnn_loto_catchment_fix import build_node_features_variant

OUT_CDMX = ROOT / "outputs" / "paper" / "cdmx"
OUT_CDMX.mkdir(parents=True, exist_ok=True)
OUT_CSV = OUT_CDMX / "cdmx_wc2026_real_validation_distance_decay.csv"
REAL_RIDERSHIP = ROOT / "data" / "cdmx" / "metro" / "wc2026_real_ridership_azteca.csv"

FEATURE_VARIANT = "distance_decay"

WC2026_DATES = ["2026-06-11", "2026-06-17", "2026-06-24", "2026-06-30"]
WC2026_MATCHES = {
    "2026-06-11": "Mexico vs South Africa (Group Stage)",
    "2026-06-17": "Colombia vs Uzbekistan (Group Stage)",
    "2026-06-24": "Czechia vs Mexico (Group Stage)",
    "2026-06-30": "Round of 32",
}


def normalize_rows(pred):
    pred = np.clip(pred, 0.0, None)
    s = pred.sum()
    return pred / s if s > 0 else np.full_like(pred, 1.0 / len(pred))


def build_real_daily_df(stations_df):
    real = pd.read_csv(REAL_RIDERSHIP, dtype={"sid": int})
    real["date"] = pd.to_datetime(real["date"]).dt.strftime("%Y-%m-%d")
    return real


def main():
    print("=" * 70)
    print(f"R2.4 CHECK: CDMX RF (feature_variant={FEATURE_VARIANT}) vs REAL WC2026 ridership")
    print("Same methodology as cdmx_wc2026_real_validation.py, only F[2] swapped")
    print("=" * 70)

    stations_df, daily_df, baseline_df, catalog_df, A_hat = load_data()
    real_df = build_real_daily_df(stations_df)
    print(f"Real WC2026 rows loaded: {len(real_df)}")

    from sklearn.ensemble import RandomForestRegressor

    Xs, ys = [], []
    for _, ev in catalog_df.iterrows():
        date_str = ev["date"]
        venue = ev["venue"]
        target = get_observed_spatial_distribution(date_str, stations_df, daily_df, baseline_df)
        if target is None:
            continue
        x = build_node_features_variant(
            date_str=date_str, stations_df=stations_df, baseline_df=baseline_df,
            daily_df=daily_df, venue_name=venue, feature_variant=FEATURE_VARIANT,
        )
        Xs.append(x.numpy())
        ys.append(target.numpy())
    Xtr = np.concatenate(Xs)
    ytr = np.concatenate(ys)
    print(f"Training RF on {len(Xs)} historical events ({len(Xtr)} rows)")

    rf = RandomForestRegressor(n_estimators=200, max_depth=10, n_jobs=-1, random_state=42)
    rf.fit(Xtr, ytr)

    catch_mask_azteca = stations_df["name"].reset_index(drop=True).isin(
        VENUE_CATCHMENT.get("Azteca", [])
    ).values

    rows = []
    for date_str in WC2026_DATES:
        day_real = real_df[real_df["date"] == date_str].set_index("sid")["riders"]
        if day_real.empty:
            print(f"  {date_str}: NO real data found -- skipping")
            continue

        day_frame = pd.DataFrame({
            "date": date_str, "sid": day_real.index.values, "riders": day_real.values,
        })
        combined_daily = pd.concat([daily_df[["date", "sid", "riders"]], day_frame], ignore_index=True)

        target = get_observed_spatial_distribution(date_str, stations_df, combined_daily, baseline_df)
        if target is None:
            print(f"  {date_str}: target construction failed -- skipping")
            continue

        real_total = float(day_real.sum())
        x = build_node_features_variant(
            date_str=date_str, stations_df=stations_df, baseline_df=baseline_df,
            daily_df=combined_daily, venue_name="Azteca", feature_variant=FEATURE_VARIANT,
            proj_total=real_total,
        )
        pred = normalize_rows(rf.predict(x.numpy()))
        target_np = target.numpy()

        mae_rf_catch = float(np.abs(pred[catch_mask_azteca] - target_np[catch_mask_azteca]).mean())
        mae_rf_all = float(np.abs(pred - target_np).mean())

        hist = historical_avg_baseline(date_str, stations_df, combined_daily, baseline_df).numpy()
        mae_hist_catch = float(np.abs(hist[catch_mask_azteca] - target_np[catch_mask_azteca]).mean())
        mae_hist_all = float(np.abs(hist - target_np).mean())

        rows.append({
            "date": date_str, "match": WC2026_MATCHES.get(date_str, ""),
            "real_total_riders": real_total,
            "mae_rf_catchment": mae_rf_catch, "mae_rf_all_stations": mae_rf_all,
            "mae_hist_avg_catchment": mae_hist_catch, "mae_hist_avg_all_stations": mae_hist_all,
            "rf_improvement_vs_hist_pct": (mae_hist_catch - mae_rf_catch) / (mae_hist_catch + 1e-8) * 100,
        })
        print(f"  [{date_str}] {WC2026_MATCHES.get(date_str,''):<35} "
              f"real_total={real_total:,.0f}  "
              f"MAE_catchment: RF={mae_rf_catch:.5f} hist_avg={mae_hist_catch:.5f}  "
              f"Delta={rows[-1]['rf_improvement_vs_hist_pct']:+.1f}%")

    df = pd.DataFrame(rows)
    df.to_csv(OUT_CSV, index=False)
    print("\n" + "=" * 70)
    print(f"Mean MAE (catchment, RF): {df['mae_rf_catchment'].mean():.5f}")
    print(f"Mean MAE (catchment, hist avg): {df['mae_hist_avg_catchment'].mean():.5f}")
    print(f"Mean RF improvement over hist avg: {df['rf_improvement_vs_hist_pct'].mean():+.1f}%")
    print(f"\nSaved -> {OUT_CSV}")


if __name__ == "__main__":
    main()
