"""
Bootstrap 95% confidence intervals for k-shot FiLM improvement results.

Resampling unit: events (not seeds). The input file contains one row per
event, with the improvement value averaged across training seeds. Resampling
at the event level is the correct unit of analysis because events are the
independent experimental observations.

Two-level bootstrap for the macro-average CI:
  (1) For each bootstrap replicate, resample events within each event type.
  (2) Average the within-type means to obtain a macro-average replicate.
  This preserves the balanced weighting across types regardless of type
  sample sizes.

Input:  outputs/paper/nyc/kshot_ablation_v2_event_means.csv
        (generated by run_kshot_ablation_v2.py)

Output: outputs/paper/nyc/bootstrap_ci.csv
        outputs/paper/nyc/bootstrap_ci_aggregate.csv
        outputs/paper/comparative/figures/fig_bootstrap_ci.png
"""
import sys
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]

DATA_FILE = ROOT / "outputs/paper/nyc/kshot_ablation_v2_event_means.csv"
OUT_DIR   = ROOT / "outputs/paper/nyc"
FIG_DIR   = ROOT / "outputs/paper/comparative/figures"
OUT_DIR.mkdir(parents=True, exist_ok=True)
FIG_DIR.mkdir(parents=True, exist_ok=True)

if not DATA_FILE.exists():
    print(f"ERROR: {DATA_FILE} not found.")
    print("Run run_kshot_ablation_v2.py first to generate event-level results.")
    sys.exit(1)

np.random.seed(42)   # fixed seed for reproducible bootstrap CIs
N_BOOT = 10_000
ALPHA  = 0.05

# Human-readable labels and type groupings
TYPE_LABELS = {
    "soccer_international": "Soccer",
    "concert_pop": "Concert",
    "parade_street": "Parade",
    "race_marathon": "Marathon",
    "sports_nfl_metlife": "NFL",
}
HIGH_SIGNAL_TYPES = [
    "soccer_international",
    "parade_street",
    "race_marathon",
    "sports_nfl_metlife",
]

df = pd.read_csv(DATA_FILE)


# Per-type bootstrap CI

records = []

for event_type in df["held_out_type"].unique():
    for k in sorted(df[df["held_out_type"] == event_type]["k"].unique()):
        subset = df[(df["held_out_type"] == event_type) & (df["k"] == k)]
        improvements = subset["improvement"].values
        n = len(improvements)

        if n == 0:
            continue

        boot_means = np.array([
            np.mean(np.random.choice(improvements, size=n, replace=True))
            for _ in range(N_BOOT)
        ])

        ci_lo = np.percentile(boot_means, 100 * ALPHA / 2)
        ci_hi = np.percentile(boot_means, 100 * (1 - ALPHA / 2))
        obs_mean = np.mean(improvements)

        records.append({
            "held_out_type": event_type,
            "type_label": TYPE_LABELS[event_type],
            "k": k,
            "n_events": n,
            "mean_improvement": round(obs_mean, 2),
            "ci_lo": round(ci_lo, 2),
            "ci_hi": round(ci_hi, 2),
            "ci_width": round(ci_hi - ci_lo, 2),
            "significant": int(ci_lo > 0),
        })

ci_df = pd.DataFrame(records)
ci_out = OUT_DIR / "bootstrap_ci.csv"
ci_df.to_csv(ci_out, index=False)
print(f"\nPer-type CI saved -> {ci_out}")
print(ci_df[ci_df["k"] == 1][
    ["type_label", "n_events", "mean_improvement", "ci_lo", "ci_hi", "significant"]
].to_string(index=False))


# Aggregate bootstrap CI at k=1
#
# Two groups:
#   A) All 5 types: macro-average over type-level means
#   B) 4 high-signal types (Concert excluded): same macro-average

k1_df = ci_df[ci_df["k"] == 1].copy()


def aggregate_boot(type_list: list, label: str) -> dict:
    """
    Compute a bootstrap 95% CI for the macro-average FiLM improvement
    across a set of event types.

    The macro-average treats each type equally regardless of how many events
    it contributes. A naive per-event bootstrap would weight high-count types
    more heavily and understate uncertainty for rare types.

    Two-level procedure:
      Outer loop (N_BOOT replicates):
        For each type, resample its events with replacement and compute
        the within-type mean. Average the resulting type-level means.
      The distribution of these replicate averages gives the CI.

    Args:
        type_list: Event type keys to include (must be in TYPE_LABELS).
        label:     Human-readable group name for output.

    Returns:
        Dict with keys: group, n_types, mean_improvement, ci_lo, ci_hi,
        significant.
    """
    type_means = []
    for t in type_list:
        row = k1_df[k1_df["held_out_type"] == t]
        if len(row) == 0:
            continue
        events = df[(df["held_out_type"] == t) & (df["k"] == 1)]["improvement"].values
        type_means.append(events)

    boot_agg = []
    for _ in range(N_BOOT):
        sampled_type_means = [
            np.mean(np.random.choice(ev, size=len(ev), replace=True))
            for ev in type_means
        ]
        boot_agg.append(np.mean(sampled_type_means))

    boot_agg = np.array(boot_agg)
    obs = np.mean([np.mean(ev) for ev in type_means])
    ci_lo = np.percentile(boot_agg, 100 * ALPHA / 2)
    ci_hi = np.percentile(boot_agg, 100 * (1 - ALPHA / 2))

    return {
        "group": label,
        "n_types": len(type_means),
        "mean_improvement": round(obs, 2),
        "ci_lo": round(ci_lo, 2),
        "ci_hi": round(ci_hi, 2),
        "significant": int(ci_lo > 0),
    }


all5 = list(TYPE_LABELS.keys())
agg_records = [
    aggregate_boot(all5, "All 5 types"),
    aggregate_boot(HIGH_SIGNAL_TYPES, "High-signal (4 types, excl. Concert)"),
]
agg_df = pd.DataFrame(agg_records)
agg_out = OUT_DIR / "bootstrap_ci_aggregate.csv"
agg_df.to_csv(agg_out, index=False)
print(f"\nAggregate CI saved -> {agg_out}")
print(agg_df.to_string(index=False))


# Figure: per-type CI at k=1 (left) and improvement by k (right)

fig, axes = plt.subplots(1, 2, figsize=(13, 5))
fig.suptitle(
    "Bootstrap 95% CI - FiLM Improvement over Backbone (NYC, k-Shot LOTO)",
    fontsize=13, fontweight="bold",
)

# Left panel: per-type CI at k=1
ax = axes[0]
k1_plot = ci_df[ci_df["k"] == 1].sort_values("mean_improvement", ascending=True)

colors = []
for _, row in k1_plot.iterrows():
    if row["ci_lo"] > 0:
        colors.append("#2196F3")   # blue: CI fully above zero
    elif row["ci_hi"] < 0:
        colors.append("#F44336")   # red: CI fully below zero
    else:
        colors.append("#9E9E9E")   # grey: CI straddles zero

y_pos = np.arange(len(k1_plot))
ax.barh(y_pos, k1_plot["mean_improvement"].values, color=colors, alpha=0.75, height=0.5)

xerr_lo = k1_plot["mean_improvement"].values - k1_plot["ci_lo"].values
xerr_hi = k1_plot["ci_hi"].values - k1_plot["mean_improvement"].values
ax.errorbar(
    k1_plot["mean_improvement"].values, y_pos,
    xerr=[xerr_lo, xerr_hi],
    fmt="none", color="black", capsize=5, linewidth=1.5, capthick=1.5,
)

ax.axvline(0, color="black", linewidth=0.8, linestyle="--", alpha=0.5)
ax.set_yticks(y_pos)
ax.set_yticklabels([TYPE_LABELS[t] for t in k1_plot["held_out_type"]], fontsize=11)
ax.set_xlabel("MAE Improvement (%)", fontsize=11)
ax.set_title("k=1: Per-Type FiLM Improvement\nwith 95% Bootstrap CI", fontsize=11)

for i, (_, row) in enumerate(k1_plot.iterrows()):
    offset = 1.5
    ha = "left" if row["mean_improvement"] >= 0 else "right"
    x  = row["mean_improvement"] + offset if row["mean_improvement"] >= 0 else row["mean_improvement"] - offset
    ax.text(x, i, f"n={int(row['n_events'])}", va="center", ha=ha, fontsize=9)

legend_patches = [
    mpatches.Patch(color="#2196F3", alpha=0.75, label="Sig. positive (CI > 0)"),
    mpatches.Patch(color="#9E9E9E", alpha=0.75, label="Not significant"),
    mpatches.Patch(color="#F44336", alpha=0.75, label="Sig. negative (CI < 0)"),
]
ax.legend(handles=legend_patches, fontsize=8, loc="lower right")

# Right panel: improvement across k values for each type
ax2 = axes[1]
type_colors = {
    "soccer_international": "#4CAF50",
    "concert_pop":          "#FF9800",
    "parade_street":        "#9C27B0",
    "race_marathon":        "#2196F3",
    "sports_nfl_metlife":   "#F44336",
}

for event_type in df["held_out_type"].unique():
    type_ci = ci_df[ci_df["held_out_type"] == event_type].sort_values("k")
    ks    = type_ci["k"].values
    means = type_ci["mean_improvement"].values
    lo    = type_ci["ci_lo"].values
    hi    = type_ci["ci_hi"].values
    color = type_colors[event_type]
    ax2.plot(ks, means, "o-", color=color, label=TYPE_LABELS[event_type],
             linewidth=2, markersize=6)
    ax2.fill_between(ks, lo, hi, color=color, alpha=0.15)

ax2.axhline(0, color="black", linewidth=0.8, linestyle="--", alpha=0.5)
ax2.set_xlabel("k (training shots)", fontsize=11)
ax2.set_ylabel("MAE Improvement (%)", fontsize=11)
ax2.set_title("FiLM Improvement by k\nwith 95% Bootstrap CI Bands", fontsize=11)
ax2.legend(fontsize=9, loc="upper left")
ax2.set_xticks(sorted(df["k"].unique()))

plt.tight_layout()
fig_path = FIG_DIR / "fig_bootstrap_ci.png"
plt.savefig(fig_path, dpi=150, bbox_inches="tight")
print(f"\nFigure saved -> {fig_path}")


# Summary table for paper

print("\n" + "=" * 70)
print("PAPER TABLE: k=1 Bootstrap 95% CI")
print("=" * 70)
print(f"{'Type':<30} {'n':>4} {'Mean':>8} {'CI 95%':>20} {'Sig?':>6}")
print("-" * 70)
for _, row in (
    ci_df[ci_df["k"] == 1]
    .sort_values("mean_improvement", ascending=False)
    .iterrows()
):
    sig = "Y" if row["significant"] else "N"
    print(
        f"{row['type_label']:<30} {int(row['n_events']):>4} "
        f"{row['mean_improvement']:>7.1f}%  "
        f"[{row['ci_lo']:>6.1f}%, {row['ci_hi']:>6.1f}%]  {sig}"
    )
print("-" * 70)
print("\nAggregate:")
for _, row in agg_df.iterrows():
    sig = "Y" if row["significant"] else "N"
    print(
        f"  {row['group']:<40} {row['mean_improvement']:>7.1f}%  "
        f"[{row['ci_lo']:>6.1f}%, {row['ci_hi']:>6.1f}%]  {sig}"
    )

print(f"\nNote: Bootstrap N={N_BOOT:,} iterations. Significance = 95% CI excludes zero.")
